// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 reads `migrations.seed` (the legacy `prisma.seed` block in
    // package.json is ignored). The seed script is plain TypeScript so we
    // run it through ts-node. `--transpile-only` skips type-checking
    // (the prod tsconfig doesn't include @types/node in `types`, and we
    // don't need a full type-check just to run a one-off seeder).
    seed: "npx ts-node --transpile-only prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
