// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 reads `migrations.seed` (the legacy `prisma.seed` block in
    // package.json is ignored). The seed script lives in `prisma/seed.ts`
    // which the project tsconfig.json doesn't cover (its implied rootDir
    // is `src/`). We point ts-node at a dedicated `prisma/tsconfig.json`
    // so it gets a self-contained config — no rootDir / @types/node /
    // verbatimModuleSyntax friction. `--transpile-only` skips full
    // type-checking which is fine for a one-off seeder.
    seed: "npx ts-node --transpile-only --project prisma/tsconfig.json prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
