/**
 * Property 12: Email Format Validation
 *
 * For all inputs `s`, `validateEmail(s).valid` is true iff:
 *   (a) `typeof s === 'string'`,
 *   (b) the regex `/^[^\s@]+@[^\s@]+\.[^\s@]+$/` matches `s`, AND
 *   (c) `s.length <= 254`.
 *
 * This is the universal characterisation specified in the design document
 * for Property 12. The validator must agree with this oracle on every input.
 *
 * Tag: Feature: voka-seat-system, Property 12: Email Format Validation
 * **Validates: Requirements 13.6, 14.1**
 */

import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import {
  validateEmail,
  EMAIL_FORMAT_REGEX,
  EMAIL_MAX_LENGTH,
} from '../../src/validators/emailValidator';

/**
 * Reference oracle expressed in the exact shape the property requires.
 * Mirrors the validator's contract without re-using its branches.
 */
const REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function oracleAccepts(input: unknown): boolean {
  return (
    typeof input === 'string' &&
    input.length <= 254 &&
    REGEX.test(input)
  );
}

describe('Feature: voka-seat-system, Property 12: Email Format Validation', () => {
  /**
   * Sanity-check the validator's own exported constants stay aligned with the
   * design's oracle, so an accidental drift in either side trips this test.
   */
  it('exports the design-mandated regex and max length', () => {
    expect(EMAIL_FORMAT_REGEX.source).toBe(REGEX.source);
    expect(EMAIL_MAX_LENGTH).toBe(254);
  });

  /**
   * Universal property: validator agrees with the oracle on every string.
   * Uses fast-check's unicode generator so we exercise random garbage,
   * non-ASCII local parts, and assorted control characters.
   */
  it('validateEmail(s).valid === oracle(s) for arbitrary unicode strings', () => {
    fc.assert(
      fc.property(fc.string({ maxLength: 300, unit: 'binary' }), (s) => {
        expect(validateEmail(s).valid).toBe(oracleAccepts(s));
      }),
      { numRuns: 500 }
    );
  });

  /**
   * Well-formed emails generated by fast-check's emailAddress arbitrary
   * MUST always be accepted (they're under 254 chars and match the regex).
   */
  it('accepts well-formed emails generated by fc.emailAddress()', () => {
    fc.assert(
      fc.property(fc.emailAddress(), (email) => {
        // Pre-condition: fc.emailAddress() emits short, regex-valid strings.
        expect(REGEX.test(email)).toBe(true);
        expect(email.length).toBeLessThanOrEqual(EMAIL_MAX_LENGTH);
        expect(validateEmail(email)).toEqual({ valid: true });
      }),
      { numRuns: 200 }
    );
  });

  /**
   * Composed local@domain.tld emails (mix of unicode local parts) must be
   * accepted whenever they fit the regex and length budget.
   */
  it('accepts composed local@domain.tld emails with unicode local parts', () => {
    const safeChar = fc
      .string({ minLength: 1, maxLength: 1, unit: 'grapheme' })
      .filter((c) => !/[\s@]/.test(c));
    const segment = fc
      .array(safeChar, { minLength: 1, maxLength: 8 })
      .map((chars) => chars.join(''));

    fc.assert(
      fc.property(segment, segment, segment, (local, domain, tld) => {
        const candidate = `${local}@${domain}.${tld}`;
        // Filter rather than fail: some unicode strings normalise to nothing
        // visible and would already be rejected by the regex on either side.
        fc.pre(candidate.length <= EMAIL_MAX_LENGTH);
        fc.pre(REGEX.test(candidate));
        expect(validateEmail(candidate)).toEqual({ valid: true });
      }),
      { numRuns: 200 }
    );
  });

  /**
   * Strings with no '@' must be rejected.
   */
  it('rejects strings containing no @ symbol', () => {
    const noAt = fc
      .string({ minLength: 1, maxLength: 50, unit: 'binary' })
      .filter((s) => !s.includes('@'));
    fc.assert(
      fc.property(noAt, (s) => {
        const result = validateEmail(s);
        expect(result.valid).toBe(false);
      }),
      { numRuns: 200 }
    );
  });

  /**
   * Strings with no '.' after the '@' must be rejected.
   */
  it('rejects strings without a dot in the domain part', () => {
    const dotless = fc
      .string({ minLength: 1, maxLength: 50, unit: 'binary' })
      .filter((s) => !s.includes('.'));
    fc.assert(
      fc.property(dotless, (s) => {
        const result = validateEmail(s);
        expect(result.valid).toBe(false);
      }),
      { numRuns: 200 }
    );
  });

  /**
   * Strings with leading or trailing whitespace must be rejected because
   * the regex's [^\s@] character classes forbid whitespace anywhere.
   */
  it('rejects strings with leading or trailing whitespace', () => {
    const whitespace = fc.constantFrom(' ', '\t', '\n', '\r');
    fc.assert(
      fc.property(
        fc.emailAddress(),
        whitespace,
        fc.boolean(),
        (email, ws, leading) => {
          const padded = leading ? `${ws}${email}` : `${email}${ws}`;
          expect(validateEmail(padded).valid).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Strings containing more than one '@' must be rejected because the regex
   * forbids '@' in either side of the split.
   */
  it('rejects strings containing multiple @ symbols', () => {
    fc.assert(
      fc.property(
        fc.emailAddress(),
        fc.emailAddress(),
        (a, b) => {
          const candidate = `${a}@${b}`;
          // Two emails joined by '@' guarantees ≥ 3 '@' chars total.
          expect(candidate.split('@').length).toBeGreaterThanOrEqual(3);
          expect(validateEmail(candidate).valid).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Edge length cases: empty string, single char, exactly 254, exactly 255.
   * These are explicit examples — not random — so we use unit-style asserts
   * inside an `it` block.
   */
  it('handles edge lengths (0, 1, 254, 255) correctly', () => {
    // Length 0: empty string, must be rejected.
    expect(validateEmail('').valid).toBe(false);

    // Length 1: cannot match the regex (needs @ and .), must be rejected.
    expect(validateEmail('a').valid).toBe(false);

    // Length exactly 254 with a valid shape: build "a"*X + "@b.cc"
    // suffix "@b.cc" is 5 chars, so prefix must be 249 'a's.
    const at254 = 'a'.repeat(249) + '@b.cc';
    expect(at254.length).toBe(254);
    expect(REGEX.test(at254)).toBe(true);
    expect(validateEmail(at254)).toEqual({ valid: true });

    // Length exactly 255 with the same valid shape, must be rejected by length.
    const at255 = 'a'.repeat(250) + '@b.cc';
    expect(at255.length).toBe(255);
    expect(REGEX.test(at255)).toBe(true);
    const result255 = validateEmail(at255);
    expect(result255.valid).toBe(false);
    if (!result255.valid) {
      expect(result255.error.toLowerCase()).toContain('254');
    }
  });

  /**
   * Length-boundary property: any regex-valid string longer than 254 chars
   * is rejected, and any regex-valid string of length ≤ 254 is accepted.
   */
  it('rejects regex-valid strings longer than 254 chars and accepts those ≤ 254', () => {
    fc.assert(
      fc.property(fc.integer({ min: 1, max: 400 }), (prefixLen) => {
        const candidate = 'a'.repeat(prefixLen) + '@b.cc';
        const expected = candidate.length <= EMAIL_MAX_LENGTH;
        expect(validateEmail(candidate).valid).toBe(expected);
      }),
      { numRuns: 200 }
    );
  });

  /**
   * Non-string inputs must be rejected (Property 12 clause `typeof s === 'string'`).
   */
  it('rejects non-string inputs', () => {
    const nonStrings: unknown[] = [
      null,
      undefined,
      0,
      1,
      42,
      true,
      false,
      {},
      { email: 'a@b.cc' },
      [],
      ['a@b.cc'],
      Symbol('x'),
    ];
    for (const value of nonStrings) {
      expect(validateEmail(value).valid).toBe(false);
    }
  });
});
